version: '3.4'

services:
  library.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__LibraryConnectionString=Server=db;Database=master;User=sa;Password=test$$123;
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db:
    environment:
      SA_PASSWORD: "test$$123"
      ACCEPT_EULA: "Y"