version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: src/Library.API/Dockerfile
    ports:
      - "5000:443"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"